language: ruby
rvm:
  - 2.1

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true

script:
  - "wget https://github.com/validator/validator.github.io/releases/download/20140222/vnu-20140222.zip"

notifications:
  email: false

# whitelist
branches:
  only:
    - gh-pages
